# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

- stage: Plan
  jobs:
  - job: terraform_plan
    displayName: "[PLAN] ${{ variables['Build.DefinitionName'] }}"
    pool: 'Default'
    steps:
    - bash: |
        echo "##[section]Starting: Terraform Init"
        terraform init -upgrade
        echo "##[section]Starting: Terraform Plan"
        terraform plan -out='./terraform/plan.tfplan' -input=false
      displayName: 'Run Terraform Init and Plan'

- stage: Apply
  jobs:
  - job: terraform_plan
    displayName: "[PLAN] ${{ variables['Build.DefinitionName'] }}"
    pool: 'Default'
    steps:
    - bash: |
        echo "##[section]Starting: Terraform Init"
        terraform init -upgrade
        echo "##[section]Starting: Terraform Plan"
        terraform plan -out='./terraform/plan.tfplan' -input=false
        terraform apply -auto-approve './terraform/plan.tfplan'
      displayName: 'Run Terraform Init and Plan'
