services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:azurite
    environment:
      - ADO_ORG=/run/secrets/ADO_ORG

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: unless-stopped

secrets:
  ADO_ORG:
    file: ../../../ADO_ORG.txt