version: "3"

secrets:
  env_secrets:
    file: ../.env

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:azurite
    secrets:
      - env_secrets
    environment:
      ENV_SECRETS_FILE: /run/secrets/env_secrets

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: unless-stopped
